/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.depot.uad.anonymizer;

import com.liferay.depot.model.DepotEntryGroupRel;
import com.liferay.depot.service.DepotEntryGroupRelLocalService;
import com.liferay.depot.uad.constants.DepotUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the depot entry group rel UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link DepotEntryGroupRelUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseDepotEntryGroupRelUADAnonymizer
	extends DynamicQueryUADAnonymizer<DepotEntryGroupRel> {

	@Override
	public void autoAnonymize(
			DepotEntryGroupRel depotEntryGroupRel, long userId,
			User anonymousUser)
		throws PortalException {

		if (depotEntryGroupRel.getUserId() == userId) {
			depotEntryGroupRel.setUserId(anonymousUser.getUserId());
			depotEntryGroupRel.setUserName(anonymousUser.getFullName());
		}

		depotEntryGroupRelLocalService.updateDepotEntryGroupRel(
			depotEntryGroupRel);
	}

	@Override
	public void delete(DepotEntryGroupRel depotEntryGroupRel)
		throws PortalException {

		depotEntryGroupRelLocalService.deleteDepotEntryGroupRel(
			depotEntryGroupRel);
	}

	@Override
	public Class<DepotEntryGroupRel> getTypeClass() {
		return DepotEntryGroupRel.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return depotEntryGroupRelLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return DepotUADConstants.USER_ID_FIELD_NAMES_DEPOT_ENTRY_GROUP_REL;
	}

	@Reference
	protected DepotEntryGroupRelLocalService depotEntryGroupRelLocalService;

}