/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.model.impl;

import com.liferay.document.library.kernel.model.DLFileEntryFriendlyURL;
import com.liferay.document.library.kernel.model.DLFileEntryFriendlyURLModel;
import com.liferay.document.library.kernel.model.DLFileEntryFriendlyURLSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DLFileEntryFriendlyURL service. Represents a row in the &quot;DLFileEntryFriendlyURL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DLFileEntryFriendlyURLModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DLFileEntryFriendlyURLImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DLFileEntryFriendlyURLImpl
 * @generated
 */
@JSON(strict = true)
public class DLFileEntryFriendlyURLModelImpl
	extends BaseModelImpl<DLFileEntryFriendlyURL>
	implements DLFileEntryFriendlyURLModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dl file entry friendly url model instance should use the <code>DLFileEntryFriendlyURL</code> interface instead.
	 */
	public static final String TABLE_NAME = "DLFileEntryFriendlyURL";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"fileEntryFriendlyURLId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"fileEntryId", Types.BIGINT}, {"friendlyURL", Types.VARCHAR},
		{"languageId", Types.VARCHAR}, {"lastPublishDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileEntryFriendlyURLId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fileEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("friendlyURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("languageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DLFileEntryFriendlyURL (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,fileEntryFriendlyURLId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,fileEntryId LONG,friendlyURL VARCHAR(75) null,languageId VARCHAR(75) null,lastPublishDate DATE null,primary key (fileEntryFriendlyURLId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table DLFileEntryFriendlyURL";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dlFileEntryFriendlyURL.fileEntryFriendlyURLId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DLFileEntryFriendlyURL.fileEntryFriendlyURLId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEENTRYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FRIENDLYURL_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LANGUAGEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FILEENTRYFRIENDLYURLID_COLUMN_BITMASK = 64L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static DLFileEntryFriendlyURL toModel(
		DLFileEntryFriendlyURLSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		DLFileEntryFriendlyURL model = new DLFileEntryFriendlyURLImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setCtCollectionId(soapModel.getCtCollectionId());
		model.setUuid(soapModel.getUuid());
		model.setFileEntryFriendlyURLId(soapModel.getFileEntryFriendlyURLId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setFileEntryId(soapModel.getFileEntryId());
		model.setFriendlyURL(soapModel.getFriendlyURL());
		model.setLanguageId(soapModel.getLanguageId());
		model.setLastPublishDate(soapModel.getLastPublishDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<DLFileEntryFriendlyURL> toModels(
		DLFileEntryFriendlyURLSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<DLFileEntryFriendlyURL> models =
			new ArrayList<DLFileEntryFriendlyURL>(soapModels.length);

		for (DLFileEntryFriendlyURLSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.document.library.kernel.model.DLFileEntryFriendlyURL"));

	public DLFileEntryFriendlyURLModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fileEntryFriendlyURLId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFileEntryFriendlyURLId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fileEntryFriendlyURLId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DLFileEntryFriendlyURL.class;
	}

	@Override
	public String getModelClassName() {
		return DLFileEntryFriendlyURL.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DLFileEntryFriendlyURL, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DLFileEntryFriendlyURL, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DLFileEntryFriendlyURL, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DLFileEntryFriendlyURL)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DLFileEntryFriendlyURL, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DLFileEntryFriendlyURL, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DLFileEntryFriendlyURL)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DLFileEntryFriendlyURL, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DLFileEntryFriendlyURL, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DLFileEntryFriendlyURL>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DLFileEntryFriendlyURL.class.getClassLoader(),
			DLFileEntryFriendlyURL.class, ModelWrapper.class);

		try {
			Constructor<DLFileEntryFriendlyURL> constructor =
				(Constructor<DLFileEntryFriendlyURL>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<DLFileEntryFriendlyURL, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DLFileEntryFriendlyURL, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DLFileEntryFriendlyURL, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<DLFileEntryFriendlyURL, Object>>();
		Map<String, BiConsumer<DLFileEntryFriendlyURL, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<DLFileEntryFriendlyURL, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", DLFileEntryFriendlyURL::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<DLFileEntryFriendlyURL, Long>)
				DLFileEntryFriendlyURL::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", DLFileEntryFriendlyURL::getCtCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<DLFileEntryFriendlyURL, Long>)
				DLFileEntryFriendlyURL::setCtCollectionId);
		attributeGetterFunctions.put("uuid", DLFileEntryFriendlyURL::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<DLFileEntryFriendlyURL, String>)
				DLFileEntryFriendlyURL::setUuid);
		attributeGetterFunctions.put(
			"fileEntryFriendlyURLId",
			DLFileEntryFriendlyURL::getFileEntryFriendlyURLId);
		attributeSetterBiConsumers.put(
			"fileEntryFriendlyURLId",
			(BiConsumer<DLFileEntryFriendlyURL, Long>)
				DLFileEntryFriendlyURL::setFileEntryFriendlyURLId);
		attributeGetterFunctions.put(
			"groupId", DLFileEntryFriendlyURL::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<DLFileEntryFriendlyURL, Long>)
				DLFileEntryFriendlyURL::setGroupId);
		attributeGetterFunctions.put(
			"companyId", DLFileEntryFriendlyURL::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DLFileEntryFriendlyURL, Long>)
				DLFileEntryFriendlyURL::setCompanyId);
		attributeGetterFunctions.put(
			"userId", DLFileEntryFriendlyURL::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<DLFileEntryFriendlyURL, Long>)
				DLFileEntryFriendlyURL::setUserId);
		attributeGetterFunctions.put(
			"userName", DLFileEntryFriendlyURL::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DLFileEntryFriendlyURL, String>)
				DLFileEntryFriendlyURL::setUserName);
		attributeGetterFunctions.put(
			"createDate", DLFileEntryFriendlyURL::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DLFileEntryFriendlyURL, Date>)
				DLFileEntryFriendlyURL::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DLFileEntryFriendlyURL::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DLFileEntryFriendlyURL, Date>)
				DLFileEntryFriendlyURL::setModifiedDate);
		attributeGetterFunctions.put(
			"fileEntryId", DLFileEntryFriendlyURL::getFileEntryId);
		attributeSetterBiConsumers.put(
			"fileEntryId",
			(BiConsumer<DLFileEntryFriendlyURL, Long>)
				DLFileEntryFriendlyURL::setFileEntryId);
		attributeGetterFunctions.put(
			"friendlyURL", DLFileEntryFriendlyURL::getFriendlyURL);
		attributeSetterBiConsumers.put(
			"friendlyURL",
			(BiConsumer<DLFileEntryFriendlyURL, String>)
				DLFileEntryFriendlyURL::setFriendlyURL);
		attributeGetterFunctions.put(
			"languageId", DLFileEntryFriendlyURL::getLanguageId);
		attributeSetterBiConsumers.put(
			"languageId",
			(BiConsumer<DLFileEntryFriendlyURL, String>)
				DLFileEntryFriendlyURL::setLanguageId);
		attributeGetterFunctions.put(
			"lastPublishDate", DLFileEntryFriendlyURL::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<DLFileEntryFriendlyURL, Date>)
				DLFileEntryFriendlyURL::setLastPublishDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFileEntryFriendlyURLId() {
		return _fileEntryFriendlyURLId;
	}

	@Override
	public void setFileEntryFriendlyURLId(long fileEntryFriendlyURLId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryFriendlyURLId = fileEntryFriendlyURLId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getFileEntryId() {
		return _fileEntryId;
	}

	@Override
	public void setFileEntryId(long fileEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fileEntryId = fileEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFileEntryId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("fileEntryId"));
	}

	@JSON
	@Override
	public String getFriendlyURL() {
		if (_friendlyURL == null) {
			return "";
		}
		else {
			return _friendlyURL;
		}
	}

	@Override
	public void setFriendlyURL(String friendlyURL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_friendlyURL = friendlyURL;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFriendlyURL() {
		return getColumnOriginalValue("friendlyURL");
	}

	@JSON
	@Override
	public String getLanguageId() {
		if (_languageId == null) {
			return "";
		}
		else {
			return _languageId;
		}
	}

	@Override
	public void setLanguageId(String languageId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_languageId = languageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalLanguageId() {
		return getColumnOriginalValue("languageId");
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastPublishDate = lastPublishDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DLFileEntryFriendlyURL.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DLFileEntryFriendlyURL.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DLFileEntryFriendlyURL toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DLFileEntryFriendlyURL>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DLFileEntryFriendlyURLImpl dlFileEntryFriendlyURLImpl =
			new DLFileEntryFriendlyURLImpl();

		dlFileEntryFriendlyURLImpl.setMvccVersion(getMvccVersion());
		dlFileEntryFriendlyURLImpl.setCtCollectionId(getCtCollectionId());
		dlFileEntryFriendlyURLImpl.setUuid(getUuid());
		dlFileEntryFriendlyURLImpl.setFileEntryFriendlyURLId(
			getFileEntryFriendlyURLId());
		dlFileEntryFriendlyURLImpl.setGroupId(getGroupId());
		dlFileEntryFriendlyURLImpl.setCompanyId(getCompanyId());
		dlFileEntryFriendlyURLImpl.setUserId(getUserId());
		dlFileEntryFriendlyURLImpl.setUserName(getUserName());
		dlFileEntryFriendlyURLImpl.setCreateDate(getCreateDate());
		dlFileEntryFriendlyURLImpl.setModifiedDate(getModifiedDate());
		dlFileEntryFriendlyURLImpl.setFileEntryId(getFileEntryId());
		dlFileEntryFriendlyURLImpl.setFriendlyURL(getFriendlyURL());
		dlFileEntryFriendlyURLImpl.setLanguageId(getLanguageId());
		dlFileEntryFriendlyURLImpl.setLastPublishDate(getLastPublishDate());

		dlFileEntryFriendlyURLImpl.resetOriginalValues();

		return dlFileEntryFriendlyURLImpl;
	}

	@Override
	public DLFileEntryFriendlyURL cloneWithOriginalValues() {
		DLFileEntryFriendlyURLImpl dlFileEntryFriendlyURLImpl =
			new DLFileEntryFriendlyURLImpl();

		dlFileEntryFriendlyURLImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		dlFileEntryFriendlyURLImpl.setCtCollectionId(
			this.<Long>getColumnOriginalValue("ctCollectionId"));
		dlFileEntryFriendlyURLImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		dlFileEntryFriendlyURLImpl.setFileEntryFriendlyURLId(
			this.<Long>getColumnOriginalValue("fileEntryFriendlyURLId"));
		dlFileEntryFriendlyURLImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		dlFileEntryFriendlyURLImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		dlFileEntryFriendlyURLImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		dlFileEntryFriendlyURLImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		dlFileEntryFriendlyURLImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		dlFileEntryFriendlyURLImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		dlFileEntryFriendlyURLImpl.setFileEntryId(
			this.<Long>getColumnOriginalValue("fileEntryId"));
		dlFileEntryFriendlyURLImpl.setFriendlyURL(
			this.<String>getColumnOriginalValue("friendlyURL"));
		dlFileEntryFriendlyURLImpl.setLanguageId(
			this.<String>getColumnOriginalValue("languageId"));
		dlFileEntryFriendlyURLImpl.setLastPublishDate(
			this.<Date>getColumnOriginalValue("lastPublishDate"));

		return dlFileEntryFriendlyURLImpl;
	}

	@Override
	public int compareTo(DLFileEntryFriendlyURL dlFileEntryFriendlyURL) {
		long primaryKey = dlFileEntryFriendlyURL.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DLFileEntryFriendlyURL)) {
			return false;
		}

		DLFileEntryFriendlyURL dlFileEntryFriendlyURL =
			(DLFileEntryFriendlyURL)object;

		long primaryKey = dlFileEntryFriendlyURL.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DLFileEntryFriendlyURL> toCacheModel() {
		DLFileEntryFriendlyURLCacheModel dlFileEntryFriendlyURLCacheModel =
			new DLFileEntryFriendlyURLCacheModel();

		dlFileEntryFriendlyURLCacheModel.mvccVersion = getMvccVersion();

		dlFileEntryFriendlyURLCacheModel.ctCollectionId = getCtCollectionId();

		dlFileEntryFriendlyURLCacheModel.uuid = getUuid();

		String uuid = dlFileEntryFriendlyURLCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dlFileEntryFriendlyURLCacheModel.uuid = null;
		}

		dlFileEntryFriendlyURLCacheModel.fileEntryFriendlyURLId =
			getFileEntryFriendlyURLId();

		dlFileEntryFriendlyURLCacheModel.groupId = getGroupId();

		dlFileEntryFriendlyURLCacheModel.companyId = getCompanyId();

		dlFileEntryFriendlyURLCacheModel.userId = getUserId();

		dlFileEntryFriendlyURLCacheModel.userName = getUserName();

		String userName = dlFileEntryFriendlyURLCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dlFileEntryFriendlyURLCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dlFileEntryFriendlyURLCacheModel.createDate = createDate.getTime();
		}
		else {
			dlFileEntryFriendlyURLCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dlFileEntryFriendlyURLCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			dlFileEntryFriendlyURLCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dlFileEntryFriendlyURLCacheModel.fileEntryId = getFileEntryId();

		dlFileEntryFriendlyURLCacheModel.friendlyURL = getFriendlyURL();

		String friendlyURL = dlFileEntryFriendlyURLCacheModel.friendlyURL;

		if ((friendlyURL != null) && (friendlyURL.length() == 0)) {
			dlFileEntryFriendlyURLCacheModel.friendlyURL = null;
		}

		dlFileEntryFriendlyURLCacheModel.languageId = getLanguageId();

		String languageId = dlFileEntryFriendlyURLCacheModel.languageId;

		if ((languageId != null) && (languageId.length() == 0)) {
			dlFileEntryFriendlyURLCacheModel.languageId = null;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			dlFileEntryFriendlyURLCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			dlFileEntryFriendlyURLCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		return dlFileEntryFriendlyURLCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DLFileEntryFriendlyURL, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DLFileEntryFriendlyURL, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DLFileEntryFriendlyURL, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DLFileEntryFriendlyURL)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DLFileEntryFriendlyURL, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DLFileEntryFriendlyURL, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DLFileEntryFriendlyURL, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((DLFileEntryFriendlyURL)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DLFileEntryFriendlyURL>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _fileEntryFriendlyURLId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _fileEntryId;
	private String _friendlyURL;
	private String _languageId;
	private Date _lastPublishDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<DLFileEntryFriendlyURL, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DLFileEntryFriendlyURL)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("ctCollectionId", _ctCollectionId);
		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"fileEntryFriendlyURLId", _fileEntryFriendlyURLId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("fileEntryId", _fileEntryId);
		_columnOriginalValues.put("friendlyURL", _friendlyURL);
		_columnOriginalValues.put("languageId", _languageId);
		_columnOriginalValues.put("lastPublishDate", _lastPublishDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ctCollectionId", 2L);

		columnBitmasks.put("uuid_", 4L);

		columnBitmasks.put("fileEntryFriendlyURLId", 8L);

		columnBitmasks.put("groupId", 16L);

		columnBitmasks.put("companyId", 32L);

		columnBitmasks.put("userId", 64L);

		columnBitmasks.put("userName", 128L);

		columnBitmasks.put("createDate", 256L);

		columnBitmasks.put("modifiedDate", 512L);

		columnBitmasks.put("fileEntryId", 1024L);

		columnBitmasks.put("friendlyURL", 2048L);

		columnBitmasks.put("languageId", 4096L);

		columnBitmasks.put("lastPublishDate", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DLFileEntryFriendlyURL _escapedModel;

}