/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.model.impl;

import com.liferay.document.library.kernel.model.DLFileEntryFriendlyURL;
import com.liferay.document.library.kernel.service.DLFileEntryFriendlyURLLocalServiceUtil;

/**
 * The extended model base implementation for the DLFileEntryFriendlyURL service. Represents a row in the &quot;DLFileEntryFriendlyURL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DLFileEntryFriendlyURLImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DLFileEntryFriendlyURLImpl
 * @see DLFileEntryFriendlyURL
 * @generated
 */
public abstract class DLFileEntryFriendlyURLBaseImpl
	extends DLFileEntryFriendlyURLModelImpl implements DLFileEntryFriendlyURL {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dl file entry friendly url model instance should use the <code>DLFileEntryFriendlyURL</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			DLFileEntryFriendlyURLLocalServiceUtil.addDLFileEntryFriendlyURL(
				this);
		}
		else {
			DLFileEntryFriendlyURLLocalServiceUtil.updateDLFileEntryFriendlyURL(
				this);
		}
	}

}