/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.service.base;

import com.liferay.document.library.kernel.model.DLFileEntryFriendlyURL;
import com.liferay.document.library.kernel.service.DLFileEntryFriendlyURLService;
import com.liferay.document.library.kernel.service.DLFileEntryFriendlyURLServiceUtil;
import com.liferay.document.library.kernel.service.persistence.DLFileEntryFriendlyURLPersistence;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;

import java.lang.reflect.Field;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dl file entry friendly url remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.documentlibrary.service.impl.DLFileEntryFriendlyURLServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.documentlibrary.service.impl.DLFileEntryFriendlyURLServiceImpl
 * @generated
 */
public abstract class DLFileEntryFriendlyURLServiceBaseImpl
	extends BaseServiceImpl
	implements DLFileEntryFriendlyURLService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DLFileEntryFriendlyURLService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DLFileEntryFriendlyURLServiceUtil</code>.
	 */

	/**
	 * Returns the dl file entry friendly url local service.
	 *
	 * @return the dl file entry friendly url local service
	 */
	public com.liferay.document.library.kernel.service.
		DLFileEntryFriendlyURLLocalService
			getDLFileEntryFriendlyURLLocalService() {

		return dlFileEntryFriendlyURLLocalService;
	}

	/**
	 * Sets the dl file entry friendly url local service.
	 *
	 * @param dlFileEntryFriendlyURLLocalService the dl file entry friendly url local service
	 */
	public void setDLFileEntryFriendlyURLLocalService(
		com.liferay.document.library.kernel.service.
			DLFileEntryFriendlyURLLocalService
				dlFileEntryFriendlyURLLocalService) {

		this.dlFileEntryFriendlyURLLocalService =
			dlFileEntryFriendlyURLLocalService;
	}

	/**
	 * Returns the dl file entry friendly url remote service.
	 *
	 * @return the dl file entry friendly url remote service
	 */
	public DLFileEntryFriendlyURLService getDLFileEntryFriendlyURLService() {
		return dlFileEntryFriendlyURLService;
	}

	/**
	 * Sets the dl file entry friendly url remote service.
	 *
	 * @param dlFileEntryFriendlyURLService the dl file entry friendly url remote service
	 */
	public void setDLFileEntryFriendlyURLService(
		DLFileEntryFriendlyURLService dlFileEntryFriendlyURLService) {

		this.dlFileEntryFriendlyURLService = dlFileEntryFriendlyURLService;
	}

	/**
	 * Returns the dl file entry friendly url persistence.
	 *
	 * @return the dl file entry friendly url persistence
	 */
	public DLFileEntryFriendlyURLPersistence
		getDLFileEntryFriendlyURLPersistence() {

		return dlFileEntryFriendlyURLPersistence;
	}

	/**
	 * Sets the dl file entry friendly url persistence.
	 *
	 * @param dlFileEntryFriendlyURLPersistence the dl file entry friendly url persistence
	 */
	public void setDLFileEntryFriendlyURLPersistence(
		DLFileEntryFriendlyURLPersistence dlFileEntryFriendlyURLPersistence) {

		this.dlFileEntryFriendlyURLPersistence =
			dlFileEntryFriendlyURLPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		_setServiceUtilService(dlFileEntryFriendlyURLService);
	}

	public void destroy() {
		_setServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DLFileEntryFriendlyURLService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DLFileEntryFriendlyURL.class;
	}

	protected String getModelClassName() {
		return DLFileEntryFriendlyURL.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				dlFileEntryFriendlyURLPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		DLFileEntryFriendlyURLService dlFileEntryFriendlyURLService) {

		try {
			Field field =
				DLFileEntryFriendlyURLServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, dlFileEntryFriendlyURLService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(
		type = com.liferay.document.library.kernel.service.DLFileEntryFriendlyURLLocalService.class
	)
	protected com.liferay.document.library.kernel.service.
		DLFileEntryFriendlyURLLocalService dlFileEntryFriendlyURLLocalService;

	@BeanReference(type = DLFileEntryFriendlyURLService.class)
	protected DLFileEntryFriendlyURLService dlFileEntryFriendlyURLService;

	@BeanReference(type = DLFileEntryFriendlyURLPersistence.class)
	protected DLFileEntryFriendlyURLPersistence
		dlFileEntryFriendlyURLPersistence;

	@BeanReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}