/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.service.base;

import com.liferay.document.library.kernel.model.DLFileEntryFriendlyURL;
import com.liferay.document.library.kernel.service.DLFileEntryFriendlyURLLocalService;
import com.liferay.document.library.kernel.service.DLFileEntryFriendlyURLLocalServiceUtil;
import com.liferay.document.library.kernel.service.persistence.DLFileEntryFriendlyURLPersistence;
import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.function.UnsafeFunction;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.service.persistence.change.tracking.CTPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dl file entry friendly url local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portlet.documentlibrary.service.impl.DLFileEntryFriendlyURLLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portlet.documentlibrary.service.impl.DLFileEntryFriendlyURLLocalServiceImpl
 * @generated
 */
public abstract class DLFileEntryFriendlyURLLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements DLFileEntryFriendlyURLLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DLFileEntryFriendlyURLLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>DLFileEntryFriendlyURLLocalServiceUtil</code>.
	 */

	/**
	 * Adds the dl file entry friendly url to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DLFileEntryFriendlyURLLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dlFileEntryFriendlyURL the dl file entry friendly url
	 * @return the dl file entry friendly url that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DLFileEntryFriendlyURL addDLFileEntryFriendlyURL(
		DLFileEntryFriendlyURL dlFileEntryFriendlyURL) {

		dlFileEntryFriendlyURL.setNew(true);

		return dlFileEntryFriendlyURLPersistence.update(dlFileEntryFriendlyURL);
	}

	/**
	 * Creates a new dl file entry friendly url with the primary key. Does not add the dl file entry friendly url to the database.
	 *
	 * @param fileEntryFriendlyURLId the primary key for the new dl file entry friendly url
	 * @return the new dl file entry friendly url
	 */
	@Override
	@Transactional(enabled = false)
	public DLFileEntryFriendlyURL createDLFileEntryFriendlyURL(
		long fileEntryFriendlyURLId) {

		return dlFileEntryFriendlyURLPersistence.create(fileEntryFriendlyURLId);
	}

	/**
	 * Deletes the dl file entry friendly url with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DLFileEntryFriendlyURLLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param fileEntryFriendlyURLId the primary key of the dl file entry friendly url
	 * @return the dl file entry friendly url that was removed
	 * @throws PortalException if a dl file entry friendly url with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DLFileEntryFriendlyURL deleteDLFileEntryFriendlyURL(
			long fileEntryFriendlyURLId)
		throws PortalException {

		return dlFileEntryFriendlyURLPersistence.remove(fileEntryFriendlyURLId);
	}

	/**
	 * Deletes the dl file entry friendly url from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DLFileEntryFriendlyURLLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dlFileEntryFriendlyURL the dl file entry friendly url
	 * @return the dl file entry friendly url that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DLFileEntryFriendlyURL deleteDLFileEntryFriendlyURL(
		DLFileEntryFriendlyURL dlFileEntryFriendlyURL) {

		return dlFileEntryFriendlyURLPersistence.remove(dlFileEntryFriendlyURL);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return dlFileEntryFriendlyURLPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DLFileEntryFriendlyURL.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dlFileEntryFriendlyURLPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portlet.documentlibrary.model.impl.DLFileEntryFriendlyURLModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return dlFileEntryFriendlyURLPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portlet.documentlibrary.model.impl.DLFileEntryFriendlyURLModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return dlFileEntryFriendlyURLPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dlFileEntryFriendlyURLPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return dlFileEntryFriendlyURLPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DLFileEntryFriendlyURL fetchDLFileEntryFriendlyURL(
		long fileEntryFriendlyURLId) {

		return dlFileEntryFriendlyURLPersistence.fetchByPrimaryKey(
			fileEntryFriendlyURLId);
	}

	/**
	 * Returns the dl file entry friendly url matching the UUID and group.
	 *
	 * @param uuid the dl file entry friendly url's UUID
	 * @param groupId the primary key of the group
	 * @return the matching dl file entry friendly url, or <code>null</code> if a matching dl file entry friendly url could not be found
	 */
	@Override
	public DLFileEntryFriendlyURL fetchDLFileEntryFriendlyURLByUuidAndGroupId(
		String uuid, long groupId) {

		return dlFileEntryFriendlyURLPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the dl file entry friendly url with the primary key.
	 *
	 * @param fileEntryFriendlyURLId the primary key of the dl file entry friendly url
	 * @return the dl file entry friendly url
	 * @throws PortalException if a dl file entry friendly url with the primary key could not be found
	 */
	@Override
	public DLFileEntryFriendlyURL getDLFileEntryFriendlyURL(
			long fileEntryFriendlyURLId)
		throws PortalException {

		return dlFileEntryFriendlyURLPersistence.findByPrimaryKey(
			fileEntryFriendlyURLId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			dlFileEntryFriendlyURLLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DLFileEntryFriendlyURL.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fileEntryFriendlyURLId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			dlFileEntryFriendlyURLLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			DLFileEntryFriendlyURL.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"fileEntryFriendlyURLId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			dlFileEntryFriendlyURLLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DLFileEntryFriendlyURL.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fileEntryFriendlyURLId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setGroupId(
			portletDataContext.getScopeGroupId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<DLFileEntryFriendlyURL>() {

				@Override
				public void performAction(
						DLFileEntryFriendlyURL dlFileEntryFriendlyURL)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, dlFileEntryFriendlyURL);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					DLFileEntryFriendlyURL.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dlFileEntryFriendlyURLPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return dlFileEntryFriendlyURLLocalService.deleteDLFileEntryFriendlyURL(
			(DLFileEntryFriendlyURL)persistedModel);
	}

	@Override
	public BasePersistence<DLFileEntryFriendlyURL> getBasePersistence() {
		return dlFileEntryFriendlyURLPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dlFileEntryFriendlyURLPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns all the dl file entry friendly urls matching the UUID and company.
	 *
	 * @param uuid the UUID of the dl file entry friendly urls
	 * @param companyId the primary key of the company
	 * @return the matching dl file entry friendly urls, or an empty list if no matches were found
	 */
	@Override
	public List<DLFileEntryFriendlyURL>
		getDLFileEntryFriendlyURLsByUuidAndCompanyId(
			String uuid, long companyId) {

		return dlFileEntryFriendlyURLPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of dl file entry friendly urls matching the UUID and company.
	 *
	 * @param uuid the UUID of the dl file entry friendly urls
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of dl file entry friendly urls
	 * @param end the upper bound of the range of dl file entry friendly urls (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching dl file entry friendly urls, or an empty list if no matches were found
	 */
	@Override
	public List<DLFileEntryFriendlyURL>
		getDLFileEntryFriendlyURLsByUuidAndCompanyId(
			String uuid, long companyId, int start, int end,
			OrderByComparator<DLFileEntryFriendlyURL> orderByComparator) {

		return dlFileEntryFriendlyURLPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the dl file entry friendly url matching the UUID and group.
	 *
	 * @param uuid the dl file entry friendly url's UUID
	 * @param groupId the primary key of the group
	 * @return the matching dl file entry friendly url
	 * @throws PortalException if a matching dl file entry friendly url could not be found
	 */
	@Override
	public DLFileEntryFriendlyURL getDLFileEntryFriendlyURLByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return dlFileEntryFriendlyURLPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the dl file entry friendly urls.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portlet.documentlibrary.model.impl.DLFileEntryFriendlyURLModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of dl file entry friendly urls
	 * @param end the upper bound of the range of dl file entry friendly urls (not inclusive)
	 * @return the range of dl file entry friendly urls
	 */
	@Override
	public List<DLFileEntryFriendlyURL> getDLFileEntryFriendlyURLs(
		int start, int end) {

		return dlFileEntryFriendlyURLPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dl file entry friendly urls.
	 *
	 * @return the number of dl file entry friendly urls
	 */
	@Override
	public int getDLFileEntryFriendlyURLsCount() {
		return dlFileEntryFriendlyURLPersistence.countAll();
	}

	/**
	 * Updates the dl file entry friendly url in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DLFileEntryFriendlyURLLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dlFileEntryFriendlyURL the dl file entry friendly url
	 * @return the dl file entry friendly url that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DLFileEntryFriendlyURL updateDLFileEntryFriendlyURL(
		DLFileEntryFriendlyURL dlFileEntryFriendlyURL) {

		return dlFileEntryFriendlyURLPersistence.update(dlFileEntryFriendlyURL);
	}

	/**
	 * Returns the dl file entry friendly url local service.
	 *
	 * @return the dl file entry friendly url local service
	 */
	public DLFileEntryFriendlyURLLocalService
		getDLFileEntryFriendlyURLLocalService() {

		return dlFileEntryFriendlyURLLocalService;
	}

	/**
	 * Sets the dl file entry friendly url local service.
	 *
	 * @param dlFileEntryFriendlyURLLocalService the dl file entry friendly url local service
	 */
	public void setDLFileEntryFriendlyURLLocalService(
		DLFileEntryFriendlyURLLocalService dlFileEntryFriendlyURLLocalService) {

		this.dlFileEntryFriendlyURLLocalService =
			dlFileEntryFriendlyURLLocalService;
	}

	/**
	 * Returns the dl file entry friendly url persistence.
	 *
	 * @return the dl file entry friendly url persistence
	 */
	public DLFileEntryFriendlyURLPersistence
		getDLFileEntryFriendlyURLPersistence() {

		return dlFileEntryFriendlyURLPersistence;
	}

	/**
	 * Sets the dl file entry friendly url persistence.
	 *
	 * @param dlFileEntryFriendlyURLPersistence the dl file entry friendly url persistence
	 */
	public void setDLFileEntryFriendlyURLPersistence(
		DLFileEntryFriendlyURLPersistence dlFileEntryFriendlyURLPersistence) {

		this.dlFileEntryFriendlyURLPersistence =
			dlFileEntryFriendlyURLPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.document.library.kernel.model.DLFileEntryFriendlyURL",
			dlFileEntryFriendlyURLLocalService);

		_setLocalServiceUtilService(dlFileEntryFriendlyURLLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.document.library.kernel.model.DLFileEntryFriendlyURL");

		_setLocalServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DLFileEntryFriendlyURLLocalService.class.getName();
	}

	@Override
	public CTPersistence<DLFileEntryFriendlyURL> getCTPersistence() {
		return dlFileEntryFriendlyURLPersistence;
	}

	@Override
	public Class<DLFileEntryFriendlyURL> getModelClass() {
		return DLFileEntryFriendlyURL.class;
	}

	@Override
	public <R, E extends Throwable> R updateWithUnsafeFunction(
			UnsafeFunction<CTPersistence<DLFileEntryFriendlyURL>, R, E>
				updateUnsafeFunction)
		throws E {

		return updateUnsafeFunction.apply(dlFileEntryFriendlyURLPersistence);
	}

	protected String getModelClassName() {
		return DLFileEntryFriendlyURL.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				dlFileEntryFriendlyURLPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		DLFileEntryFriendlyURLLocalService dlFileEntryFriendlyURLLocalService) {

		try {
			Field field =
				DLFileEntryFriendlyURLLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, dlFileEntryFriendlyURLLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(type = DLFileEntryFriendlyURLLocalService.class)
	protected DLFileEntryFriendlyURLLocalService
		dlFileEntryFriendlyURLLocalService;

	@BeanReference(type = DLFileEntryFriendlyURLPersistence.class)
	protected DLFileEntryFriendlyURLPersistence
		dlFileEntryFriendlyURLPersistence;

	@BeanReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@BeanReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}