/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.depot.uad.exporter;

import com.liferay.depot.model.DepotEntryGroupRel;
import com.liferay.depot.service.DepotEntryGroupRelLocalService;
import com.liferay.depot.uad.constants.DepotUADConstants;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.user.associated.data.exporter.DynamicQueryUADExporter;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the depot entry group rel UAD exporter.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link DepotEntryGroupRelUADExporter}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseDepotEntryGroupRelUADExporter
	extends DynamicQueryUADExporter<DepotEntryGroupRel> {

	@Override
	public Class<DepotEntryGroupRel> getTypeClass() {
		return DepotEntryGroupRel.class;
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return depotEntryGroupRelLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return DepotUADConstants.USER_ID_FIELD_NAMES_DEPOT_ENTRY_GROUP_REL;
	}

	@Override
	protected String toXmlString(DepotEntryGroupRel depotEntryGroupRel) {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.liferay.depot.model.DepotEntryGroupRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>depotEntryGroupRelId</column-name><column-value><![CDATA[");
		sb.append(depotEntryGroupRel.getDepotEntryGroupRelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(depotEntryGroupRel.getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(depotEntryGroupRel.getUserName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	@Reference
	protected DepotEntryGroupRelLocalService depotEntryGroupRelLocalService;

}